name: pytest

on:
  push:
  pull_request:

jobs:
  pytest:
    name: run tests with pytest
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: install self
        run: pip3 install .

      - name: install pytest
        run: pip3 install -U pytest

      - name: run test
        run: pytest
